[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)][def]

[def]: https://colab.research.google.com/github/LEE-Sanghoon/ITE4052/blob/main/03.Morphological_Processing.ipynb

# 형태학기반 영상처리

모폴로지 변환(Morphological Transformation)은 영상이나 이미지를 형태학적 관점에서 접근하는 기법을 의미 한다. 영상의 형태학적 특징을 분석하여 노이즈 제거, 객체 결합 및 분리, 강도 피크 검출 등에 이용 된다. 여기서 핵심은 구조화 요소(Structuring Element, 커널) 설계에 있다. 기본적인 모폴로지 기본 변환에는 침식(erosion)과 팽창(dilation)이 있다. 침식과 팽창의 변환을 기반으로 다양한 모폴로지 연산을 구현할 수 있다.

구조화 커널 모델 설계 방법
- 목적하는 영상 처리 작업에 따른 모양(shape)
  - 사각형(Rectangle): 가장 일반적이며, 수직/수평 요소를 모두 다룰 때 사용
  - 십자형(Cross): 대각선 방향의 영향을 최소화하고 수직/수평 구조 위주로 처리할 때 사용
  - 원형(Ellipse): 객체의 경계가 부드러울 때(곡선 형태) 유용하며 가장 자연스러운 형태

- 커널의 크기(ksize) 설정
  - 작은 커널(3$\times$3, 5$\times$5): 미세한 노이즈 제거, 경계가 뚜렷한 객체 처리
  - 큰 커널(7$\times$7): 큰 구멍 채우기, 두꺼운 객체 분리
  - Tip: 커널 크기가 너무 크면, 객체의 형태가 심하게 왜곡될 수 있음

- 고정점(anchor) 위치 정의   
  - default 값(-1, -1)은 커널(크기가 홀수)의 중앙점을 기준위치로 사용함
  - 커널 내에서 계산의 기준이 되는 지점. 주로 커널의 중심점으로 설정하지만, 특정 방향으로 구조를 확장해야 할 경우 위치를 이동할 수 있음

- OpenCV를 이용한 구현(Python)  
  `cv2.getStructuringElement()` 함수로 커널 생성

실습 이미지 : 
- j.png ![](https://drive.google.com/uc?export=view&id=1Ei05UvzSGQWTcDFPz4KNCcLvnMNEPmL9)
- j_dot.png ![](https://drive.google.com/uc?export=view&id=19JRSOTEg-4IsTgNRjvYrTpp4INfe6Fym)
- j_hole.png ![](https://drive.google.com/uc?export=view&id=1QJT30WHA4rzWWAq_Dy73WE2YRBRFjDP-)

In [ ]:
!wget 'https://drive.google.com/uc?export=download&id=1Ei05UvzSGQWTcDFPz4KNCcLvnMNEPmL9' -O j.png
!wget 'https://drive.google.com/uc?export=download&id=19JRSOTEg-4IsTgNRjvYrTpp4INfe6Fym' -O j_dot.png
!wget 'https://drive.google.com/uc?export=download&id=1QJT30WHA4rzWWAq_Dy73WE2YRBRFjDP-' -O j_hole.png

### 침식 Erosion

- 커널 아래의 모든 픽셀이 1인 경우 1, 그렇지 않으면 0으로 설정
- `cv2.erode(src, kernel, dst=None, anchor=None, iterations=None, boarderType=None, borderValue=None) -> dst`
  - src: 입력영상
  - kernel: 구조 요소. None을 지정하면 3$\times$3 사각형 구형 요소를 사용
  - dst: 출력영상(src와 동일 크기와 타입)
  - anshor: 고정점 위치. 기본값(-1, -1)은 중앙점 사용
  - iterations: 반복횟수. 기본값은 1, 침식 연산을 몇 번 반복할 것인지 지정
  - borderType: 가장자리 픽셀 확장 방식. 기본값은 cv2.BORDER_CONSTANT
  - borderValue: cv2.BORDER_CONSTANT인 경우, 확장된 가장자리 필셀을 채울 값.

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((5,5), np.uint8)
dst = cv2.erode(src, kernel, iterations=1)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### 팽창 Dilation

- 커널 아래의 어떤 픽실이 1인 경우 1, 그렇지 않으면 0으로 설정

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((5,5), np.uint8)
dst = cv2.dilate(src, kernel, iterations=1)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### 열림 Opening

- 열림 = 침식 → 팽창

In [ ]:
import cv2
import numpy as np

img_file = "j_dot.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((5,5), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_OPEN, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### 닫힘 Closing

- 닫힘 = 팽창 → 침식

In [ ]:
import cv2
import numpy as np

img_file = "j_hole.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((5,5), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_CLOSE, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### Morphological Gradient

- 팽창 이미지와 침식 이미지의 차

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((3,3), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_GRADIENT, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### Top-Hat

- 원본과 열림 이미지의 차(source_img - opening_img)  
    9 $\times$ 9 커널 사용

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((9,9), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_TOPHAT, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### Bottom-Hat

- 입력 이미지와 닫힘 이미지의 차  
    9 $\times$ 9 커널 사용

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = np.ones((9,9), np.uint8)
dst = cv2.morphologyEx(src, cv2.MORPH_BLACKHAT, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

### Structuring Element

- `getStructuringElement()`
  커널의 크기와 모양을 지정하여 얻을 수 있다.

```python
# Rectangular Kernel
>>> cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

>>> cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)
       
# Cross-shaped Kernel
>>> cv2.getStructuringElement(cv2.MORPH_CROSS, (5,5))
array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)
```

In [ ]:
import cv2
import numpy as np

img_file = "j.png"
src = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)

kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))
dst = cv2.morphologyEx(src, cv2.MORPH_GRADIENT, kernel)


from matplotlib import pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,5))
ax[0].imshow(src, cmap="gray"), ax[0].axis("off")
ax[1].imshow(dst, cmap="gray"), ax[1].axis("off")

plt.tight_layout()
plt.show()

----
## 참고 코드

### 이미지 업로드 방법
Colab의 작업 폴더('/content')에 이미지 파일을 업로드 한다. Google Drive를 마운트 해서 이미지 파일을 사용할 수도 있다. 이번 실습은 Colab 만으로 진행하려는 상황으로 (로컬 PC에서) 작업 이미지를 직접 업로드 하거나, wget 명령과 이미지 링크 정보를 이용하는 경우의 두 가지 방법을 진행한다.

![](https://drive.google.com/uc?export=view&id=1Ywls6xHfnvNEZ5Bxz9jUldMQDzUSqta4)

- 레나 이미지를 로컬 PC에 다운 받은 후 Colab에 업로드, 또는 공유 링크를 wget을 이용해서 직접 Colab으로 직접 다운로드 한다.

In [ ]:
# 로컬 PC에서 파일을 선택하여 업로드
from google.colab import files
uploaded = files.upload()

In [ ]:
# 알고 있는 링크 정보를 wget 명령을 통해서 Colab에 복사
!wget 'https://drive.google.com/uc?export=download&id=1Ywls6xHfnvNEZ5Bxz9jUldMQDzUSqta4' -O Lena.png

### 이미지 출력

- 이미지 객체를 생성 한다.

In [ ]:
import cv2
img = cv2.imread('Lena.png', cv2.IMREAD_COLOR)

- 코랩 환경에서 실행 할 때, `cv2_imshow` 모듈로 출력 한다.

In [ ]:
from google.colab.patches import cv2_imshow
cv2_imshow(img)